#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := esp32-tlv-test
EXTRA_COMPONENT_DIRS := $(abspath ./../) $(abspath ./../../esp32-utils)

include $(IDF_PATH)/make/project.mk


